server:
  port: ${BACKUP_APP_PORT:4934}

spring:
  application:
    name: AppBackup
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: ${BACKUP_APP_JDBC_POSTGRES_URL:jdbc:postgresql://localhost:2530/backup_app}
    username: ${BACKUP_APP_POSTGRES_USER:JIvpAwvUqKfY}
    password: ${BACKUP_APP_POSTGRES_PASSWORD:J32QAHo?8z-sBL]*}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    ROOT: INFO